In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.regularizers import L2
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.layers import Dense, LSTM, Dropout,Embedding,SimpleRNN,GRU,SpatialDropout1D,Bidirectional
from tensorflow.keras import regularizers

In [ ]:
df=pd.read_csv(r'dataset\Combined Data.csv')

In [3]:
df.head()

   Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3           3  I've shifted my focus to something else but I'...  Anxiety
4           4  I'm restless and restless, it's been a month n...  Anxiety

In [4]:
df=df.drop('Unnamed: 0',axis=1)

In [5]:
df.head()

                                           statement   status
0                                         oh my gosh  Anxiety
1  trouble sleeping, confused mind, restless hear...  Anxiety
2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3  I've shifted my focus to something else but I'...  Anxiety
4  I'm restless and restless, it's been a month n...  Anxiety

In [6]:
df['status'].value_counts()

status
Normal                  16351
Depression              15404
Suicidal                10653
Anxiety                  3888
Bipolar                  2877
Stress                   2669
Personality disorder     1201
Name: count, dtype: int64

In [7]:
df.isnull().sum()

statement    362
status         0
dtype: int64

In [8]:
df_new=df.dropna()

In [9]:
df_new.isnull().sum()

statement    0
status       0
dtype: int64

In [10]:
X=df_new.drop(['status'],axis=1)

In [11]:
Y=df_new['status']

In [12]:
X_new=X.to_numpy().tolist()

In [13]:
X_new

[['oh my gosh'],
 ['trouble sleeping, confused mind, restless heart. All out of tune'],
 ['All wrong, back off dear, forward doubt. Stay in a restless and restless place'],
 ["I've shifted my focus to something else but I'm still worried"],
 ["I'm restless and restless, it's been a month now, boy. What do you mean?"],
 ['every break, you must be nervous, like something is wrong, but what the heck'],
 ['I feel scared, anxious, what can I do? And may my family or us be protected :)'],
 ["Have you ever felt nervous but didn't know why?"],
 ["I haven't slept well for 2 days, it's like I'm restless. why huh :([]."],
 ["I'm really worried, I want to cry."],
 ["always restless every night, even though I don't know why, what's wrong. strange."],
 ["I'm confused, I'm not feeling good lately. Every time I want to sleep, I always feel restless"],
 ['sometimes what is needed when there is a problem is to laugh until you forget that there is a problem, when you remember it, you feel restless like that well, it turns out that I still have a sad burden blah blah blah'],
 ['Because this worry is you.'],
 ["Sometimes it's your own thoughts that make you anxious and afraid to close your eyes until you don't sleep"],
 ["Every time I wake up, I'm definitely nervous and excited, until when are you going to try ™‚"],
 ["I can only hope, even though I'm worried if it starts like this...."],
 ['restive = restless, restless'],
 ['"No regrets or grudges/angry at things that have passed, and not worrying too much about the future, that\'s true serenity."'],
 ["If the guy is sick, the girl actually feels sick indirectly. He must be feeling restless and restless. :')"],
 ["I've been the most anxious person before I became the most sincere person, I've also been the most worried person before it all ended"],
 ['Successfully online at 9am. Even sleeping in a state of restlessness what is wrong with me'],
 ["Can't sleep. Just restless by nature"],
 ['Already worried about picking up the phone'],
 ["a little restless. a little restless. always feel guilty. sorry if i can't be the best as i've been :'"],
 ["I've been so restless since this morning"],
 ['it makes you feel restless'],
 ['Sleepy but restless when you sleep'],
 ["Why is this cave... I'm already in a bad mood and then my heart seems to be beating really fast... I'm really nervous. Is there something wrong???"],
 ["He is very busy, He is restless, geez, what's going on?"],
 ["I'm broken and fragile, I'm hurt, I can't stand the anxiety anymore, I can't stand the love. Until now I was ignored, not seen, even left far away. I'm not like what he wants, so I'll just step back."],
 ["# Suggest a song that makes you calm, don't know why suddenly this feeling of anger / restlessness appears. Thanks!"],
 ['Terooosss nervous huuuu'],
 ["why today's heart doesn't feel good..jealous?.anxious?.disappointed?.feeling failed?"],
 ["It's a habit from elementary school if I think about something I'll get worried I can't sleep"],
 ['Since yesterday yesterday, I have not been in the mood, very sensitive, feeling restless, always surprised and many surprises every day that almost make my brain explode, everyone is the target of ups and downs in mood. But today I feel very grateful that this lecture drama is over.'],
 ["Tonight he continues to chatter about money, I'm so confused what to do. Once he said don't worry about money, but he kept blabbering about money."],
 ['Feeling so restless lately.'],
 ["Oh god I'm restless"],
 ['but my heart is still restless even though my mouth is talking'],
 ['waiting for uncertainty, please be anxious'],
 ['been the most anxious person, before becoming the most sincere person'],
 ["Did you ever read it when you read it to RL, I mean the atmosphere, the taste. It's because I'm like this. when I read au, the topic was about mental illness ™ my days became restless....and now I'm scared."],
 ['Hi, I want to tell you... Lately I\'ve been feeling restless, have trouble sleeping, I searched on google it says it\'s a mild symptom of depression, I used to tell my mom a psychologist friend "don\'t think too much, it\'s not important you get depressed easily" then I frequent irregular breathing.'],
 ["I've been feeling restless for the past few days, now I'm nauseous, like someone..."],
 ["Oh no I'm restless. The time will come. I walk with Jesus. Then my heart is calm.. Every time I sing a song I don't know, tomorrow in this section I always want to cry . Because I sing it but I don't do it . Sorry God I worry too much ️"],
 ['Controlling anxiety is not as easy as it sounds.'],
 ["Since the pandemic, I haven't opened my laptop for a day, I feel restless, I have a very heavy life load"],
 ['People who are restless and afraid can be seen from the frequent touching of the face and ringing the fingers.'],
 ["I don't know if my mind breaks down, but I don't want to think about it :( , why do I feel restless?"],
 ['Sensitive feelings make the heart restless.'],
 ["Let's not be nervous, how about ™‚"],
 ["after being confessed, I'm really nervous"],
 ['Restless.. and.. restless..'],
 ["This is the first time I've had an anxiety disorder in my sleep, and it wasn't really good. Even though I'm not thinking about anything, but I'm restless"],
 ["It's been a week I feel restless and my head feels full I want to rest while I sleep"],
 ['why am i nervous'],
 ['Anxious, all afraid, afraid of war, afraid of economic crisis, afraid of air pollution, disease outbreaks, clean water, etc. When are you happy?'],
 ['oh my god why are you so nervous'],
 ['feelings of restlessness have started to appear ±'],
 ['Very restless bgsd'],
 ["The days are full of restlessness, with income that doesn't know the direction..Hopefully we can always get what we need and be given the advantage for a desire...5 - 5 - 21"],
 ['1 hour wake up 1 hour wake up ngde the restless is here kle cak after polishing dwg'],
 ["Lately everything has been all of a sudden, suddenly happy, suddenly sad, suddenly anxious, suddenly relaxed, suddenly excited, suddenly lethargic, etc. I really don't like everything that is impromptu, yes, but what can I do? Ha ha ha"],
 ["I'm so sorry, but can you give me words of encouragement or not? I'm really worried that I can't make my kids happy."],
 ["I don't like worrying, I don't like wehhh!"],
 ['Behind your online, there is a heart that is anxiously waiting to hear from you'],
 ['nervous restless peramoy'],
 ["I'm nervous I don't know why. I don't feel calm"],
 ["Sometimes I can't even rest. Always worried, worried about this, even though I'm tired"],
 ['It feels uneasy.'],
 ["I'm so restless, I don't know why"],
 ['Day by day, that hope grows, the closer I feel, the more I expect from you, and sometimes I get anxious because of it. To the point that I became worried, worried that it would disturb my hopes. Especially disturbing km.'],
 ["Urmi has a fever, I'm already sad and restless.. What's more, this little girl has a fever, ha ha ha"],
 ['How many days have you been feeling restless at night and in the afternoon your mind is empty, why?'],
 ["From now on, it's not really good, being restless is tired by nature"],
 ["I haven't slept yet, and now my head hurts so bad. I'm sleepy, but I can't sleep, I've tried to brake but I'm restless "],
 ['Too anxious. Too worried. Too scared'],
 ['Restless and agitated.'],
 ['There will always be calm in the midst of restlessness'],
 ['dismayed = disappointed, anxious'],
 ["This is why my heart is beating so fast. Very restless. But I don't know what I'm worried about. It's a great feeling....."],
 ['More restless. Hopefully those who are there are okay.... Oh Allah protect him..... Amen, robbal alamin'],
 ["If my friends have replied to my tweet that has an opinion, I'm worried"],
 ["I'm hungry, weak, lethargic, restless."],
 ['Sudden restlessness. Why are you..'],
 ['Sleeps 3 hours, rest restless. Try a variety of positions and ways never fall asleep. I really need to be able to control this mind.'],
 ["STOP I'M GAMAU ANXIETY, GUNDAH GULANA AGAIN"],
 ['Anxious'],
 ["It's so restless work"],
 ["Is there anyone who, when sick, can't sleep well, but sleeps restlessly?"],
 ['Please worry until you want to cry'],
 ["Exam on Saturday. Saturday's Starting Presentation..On Going: CT.Place CSE Dept. .Assignments….AND UNTIL NOW CLEAR CATIA TRAINING 2 PRODUCTS HAHAHAHA.. awesome, still in sleep mode, but I'm nervous, haha"],
 ["I'm nervous, when you come change anxiety and become anxious, I'm more worried. Tomorrow I will try to live without news from you again, quickly go away from my insincerity."],
 ['How worried am I? *asked my other self. Until it was sent, sustenance had a good friend. Moved'],
 ['Restless due to imagining too long and high until lazy to sleep.'],
 ["It's like something's up, something's weird, but I don't know what, it feels so restless."],
 ['"No regrets or grudges/angry at things that have passed, and not worrying too much about the future, that\'s true serenity."'],
 ["For God's sake, I'm so tired of worrying."],
 ["For 3 years comfortable with this condition, anxiously wondering if a few days later everything will change? I don't know, another crisis of confidence"],
 ['Feeling a little anxious today.'],
 ["Not regretting or holding grudges/angry at things that have passed, and not worrying too much about the future, that's true serenity"],
 ['Please be anxious , it must continue like this.'],
 ["Hmm, I don't know what to do, but I'm nervous"],
 ["Very restless can't sleep ™"],
 ["I'm sad because I can't produce anything but I like to complain every day because I'm tired of taking care of children I see the body is getting bigger, yes I am getting more and more restless"],
 ["Every time after sunset, why must this heart be restless as if it can't accept the situation. But with this situation, you can't do anything, if you do it, it can only make things worse"],
 ['Why are you restless and restless yo ”'],
 ["I'm so nervous about what to do"],
 ['tbtb restless, tf is wrong with meh?'],
 ["I swear I can't sleep...sleep anyway, but I don't sleep...so restless.."],
 ["Why does it seem like tonight I'm restless, sad like I want to cry but I don't know what to be sad about"],
 ["why so nervous? what is certain is not because thr is without tukin. ..but it's all because of you"],
 ['The script is harmless. But continuing anxiety because the thesis is not finished can be dangerous for the heart.'],
 ["can't you not disturb people's lives? until I'm anxious and can't sleep"],
 ['how do you keep it calm, original tbtb is excited and then you\'re sweaty or nervous "'],
 ['And again suddenly feeling nervous and anxious without knowing why :(.'],
 ["I'm not feeling very good this morning, I'm really worried ”"],
 ["If you are restless & restless, just complain to your RABB and read the Qur'an so that the heart becomes cool and reduce cynicism towards others #bowochallenge #iwartabowochallenge"],
 ['controlling excessive anxiety'],
 ["When you hear the song, your heart becomes calm and when you hear the Koran, your heart becomes tense and restless.. it's a sign that your heart is hit by CORONA BLOOD.. you need to think about it.. because life is not a game."],
 ['restless restlessness haunts self'],
 ["The peak period of my stress has passed and I am only noisy now. After going out with my friends yesterday, that makes me feel kinda better. At first I was afraid and anxious to go out, yes, because anxiety is still active. But well I hope I'll gain some weight after this storm, bismillaah"],
 ["I'm most worried when my mom is sick."],
 ["don't worry yet :)"],
 ['"Yesterday, I was worried half to death, now my wife is aware of being stiff again... how about that?"'],
 ["The last time I felt this nervous was on Wednesday. When he found out his mother died. I hope this isn't a sign anymore"],
 ["I don't know how many years it took me to jump in until I could feel the descent without worrying ²"],
 ["I want to ask, have you ever been worried about the things you like? Even because you really like it, you feel like it's a part of your life. But every time you do or remember it you get worried. What do you think you should do? :("],
 ['However, every time I picket, I\'m always nervous: "Even though I\'m just a picket, I\'m really scared, I\'m excited:"'],
 ["BY GOD I'M STILL WORRY."],
 ['time goes on..days go on..at the same time my heart is getting restless and hurt...oh Allah I know you are testing me with this patience, and you are testing me with everything that happens..forgive me who is starting to weaken and lose enthusiasm for keep fighting and survive...'],
 ['I want to exhale the restlessness in my chest with my breath'],
 ["Why every morning I want to sleep I'm restless "],
 ['Anxious alone, sad alone, not having peace'],
 ["What's wrong I'm worried, oh I hope it's okay"],
 ["I really like this, I'm nervous about things I'm not sure about, I don't know why but I feel really nervous. WEIRD."],
 ["I'm so nervous, why?"],
 ['but my heart is still restless even though my mouth is talking'],
 ["Since then I was restless to the point of choking. What's wrong?"],
 ["Starting to worry again if you have a lot of schedules, even though yesterday it was neatly arranged. How come biso missed ouch :')"],
 ["Adf-my does anyone know why I am here? I've been feeling restless since yesterday, like worrying/worrying too much, suddenly feeling sad, just scared. But I also don't know why"],
 ['Gegana, restless, speechless, I don\'t know what the cause is:"'],
 ["I'm lazy.. I'm so nervous"],
 ['Happy but also worried.'],
 ["It's anxious to worry"],
 ["Honestly, I'm really nervous"],
 ['Here from now on, my heart is restless'],
 ["Later when you are tired of the new one, and then you look back and feel guilty for me, don't be a bit nervous. Trust me, I have forgiven you. Even though I will never accept you again."],
 ["I need adit not for stalking or for strange things because I myself have started to learn not to stalk just because I'm afraid that mental disorders will get worse even though I still feel anxious and afraid if I don't stalk, I can hold it so that Adit doesn't feel disturbed"],
 ['Keep restless astagfirullah'],
 ["I'm excited but I don't know why, there's no reason, I'm nervous, I have a stomach ache but I'm scared, I know I'm tired, this is the third time today, hah â€” hah :)"],
 ['Always worried about the future, even though today has not changed.'],
 ['every time you worry, why is the disease running to your stomach?'],
 ["If you're nervous looking for the best position before going to sleep, it feels like someone's watching you ™„"],
 ['Restless and agitated'],
 ['In the evening, towards the morning. A little worried, a lot of longing'],
 ["Some days, I don't think I'm doing well, so I feel like I'm really crying, scared, anxious, just sad. until I think of this when I cry, does my fast break or not?"],
 ["It's been a few days when I sleep by default I'm afraid, restless, nervous, feel alone, sometimes my breath is really heavy.....why is that... like I'm afraid of being restless, oh my God"],
 ['tired of overtingking, tired of worrying too much, tired of being tired'],
 ["aren't you worried? aren't you worried? don't you worry..."],
 ['Instead of getting calmer, this heart is getting more restless'],
 ["can i tap the dm or not? I'm very nervous thinking"],
 ['Finally restless again uhh mmhhh ahh'],
 ['No need to run, just walk one by one the stones that are being stepped on slowly and absorb it without feeling anxious and full of emotions'],
 ["Lately I'm feeling scared & very anxious thinking about the day for tomorrow's work inspector . Honestly, I'm really scared because I'm not very close to friends, I'm afraid I can't, I'm afraid to disappoint, and if I suddenly remember I cry"],
 ["This is why I can't sleep, I'm so restless..."],
 ['I want to exhale the restlessness in my chest with my breath'],
 ['Restless restlessness accompanies'],
 ['hlt! why do i like to be nervous tbtb keep worrying so much that i sweat'],
 ['Not many people are sure of their prayers, not many people are faithful to wait with what is prayed for. Prayer is unique, there is hope and feeling, there is worry and anxiety, there is tears and happiness. But the end of the prayer will always be the best for humans.'],
 ["I wonder why my heart beats like that sometimes for weeks, then it's back to normal for a few weeks, does anyone know why this isn't it? Or maybe I'm often anxious and stressed, okay?"],
 ["I'm so nervous I swear, the views are getting slower"],
 ['Just woke up feeling restless and sore ™„'],
 ["I'm so worried 5 days of not coming home wey"],
 ['My life is chaos. There is no solution. Fear of the uncertain. Restless direction.'],
 ['UNDERSTANDING FEEL FEELING«'],
 ["I really can't be told to just listen to it for hours. Immediately anxious innate."],
 ["I haven't given up… just a little restless."],
 ["Actually I'm worried. The original looks really scared. I've come to play/bite my nails :("],
 ["If I'm honest, I've been nervous since that day even though I said it wasn't...."],
 ["Lately, I've been feeling restless and restless. Haihh"],
 ["I'm so nervous, why isn't it?"],
 ["The default bat is restless, I don't know why"],
 ["you know you're restless"],
 ['Restless,. Locked in all motion. Whipped in the brain noisy debate about decisions. Make friends with fear and risk'],
 ["Wow, I'm getting restless, let's sleep"],
 ["I swear I'm so nervous, why don't you"],
 ['I was a little worried that the afternoon class would actually be able to reach the target. But God just gave a way, wednesday class was moved even though it was a quiz. At least later in the morning you can make out with data until iftar'],
 ["–¤ When you're anxious or nervous, do you feel like your heart feels weird, doesn't it? Is it just me?"],
 ["Come on, come on, let's go... 10 years could be passed before, it's not even a month yet, I'm already restless"],
 ['Time is slow for those who wait, too long for those who are restless, and too short for those who are happy'],
 ["Restless, restless, become one. Can't agree. Can't even sleep"],
 ['May May be accompanied by good news. The injured, get well soon. Sorrow turns to love. Quieter anxiety. And prayers that are more patient...#senjamu'],
 ['Since then, the chicken cake has been restless and wants to lay eggs.'],
 ['Do not compare yourself to others. Envy only makes restless soul. Be yourself.'],
 ["The 5 dream ones were moved to a new unit, so why isn't the Anjrit so worried?"],
 ["finished for the heart's intention to watch the series, I even thought about it. I'm worried"],
 ['"No regrets or grudges/angry at things that have passed, and don\'t put too much anxiety over the record period #COYS'],
 ["Usually, if you're restless for a long time, surely after that something will happen or not"],
 ["Have you ever thought of something and then immediately forgot it then thought you were thinking about this bastard, I don't remember it, so I was restless"],
 ['Dialogue in the morning.. to yourself, restless and restless accompanying it, hoping someone will understand-'],
 ["I'm the only one who's nervous."],
 ["I'm starting to worry"],
 ["In my father's family, everyone is smart, I'm sure the expectations for me are also high it makes me very anxious to think about this huhu"],
 ["Already complete. Disappointed with a broken heart. Produces a sense of restlessness. I don't know, hopefully all of this ends beautifully"],
 ['when your bipolar relapse welcome shortness of breath, tremors, anxiety, fear, selfharm etc'],
 ["How come lately I'm not feeling well, like mellow, not calm, restless"],
 ["When you think about it and don't finish it, it feels really restless"],
 ["I'm worried.. I'm in a bad mood.. but excited to see law school.."],
 ["Yes, what will happen later :'), I'm worried that I can control my emotions"],

In [14]:
X_texts_new = np.array(X_new).ravel().tolist()

In [15]:
X_texts_new

['oh my gosh',
 'trouble sleeping, confused mind, restless heart. All out of tune',
 'All wrong, back off dear, forward doubt. Stay in a restless and restless place',
 "I've shifted my focus to something else but I'm still worried",
 "I'm restless and restless, it's been a month now, boy. What do you mean?",
 'every break, you must be nervous, like something is wrong, but what the heck',
 'I feel scared, anxious, what can I do? And may my family or us be protected :)',
 "Have you ever felt nervous but didn't know why?",
 "I haven't slept well for 2 days, it's like I'm restless. why huh :([].",
 "I'm really worried, I want to cry.",
 "always restless every night, even though I don't know why, what's wrong. strange.",
 "I'm confused, I'm not feeling good lately. Every time I want to sleep, I always feel restless",
 'sometimes what is needed when there is a problem is to laugh until you forget that there is a problem, when you remember it, you feel restless like that well, it turns out that I still have a sad burden blah blah blah',
 'Because this worry is you.',
 "Sometimes it's your own thoughts that make you anxious and afraid to close your eyes until you don't sleep",
 "Every time I wake up, I'm definitely nervous and excited, until when are you going to try ™‚",
 "I can only hope, even though I'm worried if it starts like this....",
 'restive = restless, restless',
 '"No regrets or grudges/angry at things that have passed, and not worrying too much about the future, that\'s true serenity."',
 "If the guy is sick, the girl actually feels sick indirectly. He must be feeling restless and restless. :')",
 "I've been the most anxious person before I became the most sincere person, I've also been the most worried person before it all ended",
 'Successfully online at 9am. Even sleeping in a state of restlessness what is wrong with me',
 "Can't sleep. Just restless by nature",
 'Already worried about picking up the phone',
 "a little restless. a little restless. always feel guilty. sorry if i can't be the best as i've been :'",
 "I've been so restless since this morning",
 'it makes you feel restless',
 'Sleepy but restless when you sleep',
 "Why is this cave... I'm already in a bad mood and then my heart seems to be beating really fast... I'm really nervous. Is there something wrong???",
 "He is very busy, He is restless, geez, what's going on?",
 "I'm broken and fragile, I'm hurt, I can't stand the anxiety anymore, I can't stand the love. Until now I was ignored, not seen, even left far away. I'm not like what he wants, so I'll just step back.",
 "# Suggest a song that makes you calm, don't know why suddenly this feeling of anger / restlessness appears. Thanks!",
 'Terooosss nervous huuuu',
 "why today's heart doesn't feel good..jealous?.anxious?.disappointed?.feeling failed?",
 "It's a habit from elementary school if I think about something I'll get worried I can't sleep",
 'Since yesterday yesterday, I have not been in the mood, very sensitive, feeling restless, always surprised and many surprises every day that almost make my brain explode, everyone is the target of ups and downs in mood. But today I feel very grateful that this lecture drama is over.',
 "Tonight he continues to chatter about money, I'm so confused what to do. Once he said don't worry about money, but he kept blabbering about money.",
 'Feeling so restless lately.',
 "Oh god I'm restless",
 'but my heart is still restless even though my mouth is talking',
 'waiting for uncertainty, please be anxious',
 'been the most anxious person, before becoming the most sincere person',
 "Did you ever read it when you read it to RL, I mean the atmosphere, the taste. It's because I'm like this. when I read au, the topic was about mental illness ™ my days became restless....and now I'm scared.",
 'Hi, I want to tell you... Lately I\'ve been feeling restless, have trouble sleeping, I searched on google it says it\'s a mild symptom of depression, I used to tell my mom a psychologist friend "don\'t think too much, it\'s not important you get depressed easily" then I frequent irregular breathing.',
 "I've been feeling restless for the past few days, now I'm nauseous, like someone...",
 "Oh no I'm restless. The time will come. I walk with Jesus. Then my heart is calm.. Every time I sing a song I don't know, tomorrow in this section I always want to cry . Because I sing it but I don't do it . Sorry God I worry too much ️",
 'Controlling anxiety is not as easy as it sounds.',
 "Since the pandemic, I haven't opened my laptop for a day, I feel restless, I have a very heavy life load",
 'People who are restless and afraid can be seen from the frequent touching of the face and ringing the fingers.',
 "I don't know if my mind breaks down, but I don't want to think about it :( , why do I feel restless?",
 'Sensitive feelings make the heart restless.',
 "Let's not be nervous, how about ™‚",
 "after being confessed, I'm really nervous",
 'Restless.. and.. restless..',
 "This is the first time I've had an anxiety disorder in my sleep, and it wasn't really good. Even though I'm not thinking about anything, but I'm restless",
 "It's been a week I feel restless and my head feels full I want to rest while I sleep",
 'why am i nervous',
 'Anxious, all afraid, afraid of war, afraid of economic crisis, afraid of air pollution, disease outbreaks, clean water, etc. When are you happy?',
 'oh my god why are you so nervous',
 'feelings of restlessness have started to appear ±',
 'Very restless bgsd',
 "The days are full of restlessness, with income that doesn't know the direction..Hopefully we can always get what we need and be given the advantage for a desire...5 - 5 - 21",
 '1 hour wake up 1 hour wake up ngde the restless is here kle cak after polishing dwg',
 "Lately everything has been all of a sudden, suddenly happy, suddenly sad, suddenly anxious, suddenly relaxed, suddenly excited, suddenly lethargic, etc. I really don't like everything that is impromptu, yes, but what can I do? Ha ha ha",
 "I'm so sorry, but can you give me words of encouragement or not? I'm really worried that I can't make my kids happy.",
 "I don't like worrying, I don't like wehhh!",
 'Behind your online, there is a heart that is anxiously waiting to hear from you',
 'nervous restless peramoy',
 "I'm nervous I don't know why. I don't feel calm",
 "Sometimes I can't even rest. Always worried, worried about this, even though I'm tired",
 'It feels uneasy.',
 "I'm so restless, I don't know why",
 'Day by day, that hope grows, the closer I feel, the more I expect from you, and sometimes I get anxious because of it. To the point that I became worried, worried that it would disturb my hopes. Especially disturbing km.',
 "Urmi has a fever, I'm already sad and restless.. What's more, this little girl has a fever, ha ha ha",
 'How many days have you been feeling restless at night and in the afternoon your mind is empty, why?',
 "From now on, it's not really good, being restless is tired by nature",
 "I haven't slept yet, and now my head hurts so bad. I'm sleepy, but I can't sleep, I've tried to brake but I'm restless ",
 'Too anxious. Too worried. Too scared',
 'Restless and agitated.',
 'There will always be calm in the midst of restlessness',
 'dismayed = disappointed, anxious',
 "This is why my heart is beating so fast. Very restless. But I don't know what I'm worried about. It's a great feeling.....",
 'More restless. Hopefully those who are there are okay.... Oh Allah protect him..... Amen, robbal alamin',
 "If my friends have replied to my tweet that has an opinion, I'm worried",
 "I'm hungry, weak, lethargic, restless.",
 'Sudden restlessness. Why are you..',
 'Sleeps 3 hours, rest restless. Try a variety of positions and ways never fall asleep. I really need to be able to control this mind.',
 "STOP I'M GAMAU ANXIETY, GUNDAH GULANA AGAIN",
 'Anxious',
 "It's so restless work",
 "Is there anyone who, when sick, can't sleep well, but sleeps restlessly?",
 'Please worry until you want to cry',
 "Exam on Saturday. Saturday's Starting Presentation..On Going: CT.Place CSE Dept. .Assignments….AND UNTIL NOW CLEAR CATIA TRAINING 2 PRODUCTS HAHAHAHA.. awesome, still in sleep mode, but I'm nervous, haha",
 "I'm nervous, when you come change anxiety and become anxious, I'm more worried. Tomorrow I will try to live without news from you again, quickly go away from my insincerity.",
 'How worried am I? *asked my other self. Until it was sent, sustenance had a good friend. Moved',
 'Restless due to imagining too long and high until lazy to sleep.',
 "It's like something's up, something's weird, but I don't know what, it feels so restless.",
 '"No regrets or grudges/angry at things that have passed, and not worrying too much about the future, that\'s true serenity."',
 "For God's sake, I'm so tired of worrying.",
 "For 3 years comfortable with this condition, anxiously wondering if a few days later everything will change? I don't know, another crisis of confidence",
 'Feeling a little anxious today.',
 "Not regretting or holding grudges/angry at things that have passed, and not worrying too much about the future, that's true serenity",
 'Please be anxious , it must continue like this.',
 "Hmm, I don't know what to do, but I'm nervous",
 "Very restless can't sleep ™",
 "I'm sad because I can't produce anything but I like to complain every day because I'm tired of taking care of children I see the body is getting bigger, yes I am getting more and more restless",
 "Every time after sunset, why must this heart be restless as if it can't accept the situation. But with this situation, you can't do anything, if you do it, it can only make things worse",
 'Why are you restless and restless yo ”',
 "I'm so nervous about what to do",
 'tbtb restless, tf is wrong with meh?',
 "I swear I can't sleep...sleep anyway, but I don't sleep...so restless..",
 "Why does it seem like tonight I'm restless, sad like I want to cry but I don't know what to be sad about",
 "why so nervous? what is certain is not because thr is without tukin. ..but it's all because of you",
 'The script is harmless. But continuing anxiety because the thesis is not finished can be dangerous for the heart.',
 "can't you not disturb people's lives? until I'm anxious and can't sleep",
 'how do you keep it calm, original tbtb is excited and then you\'re sweaty or nervous "',
 'And again suddenly feeling nervous and anxious without knowing why :(.',
 "I'm not feeling very good this morning, I'm really worried ”",
 "If you are restless & restless, just complain to your RABB and read the Qur'an so that the heart becomes cool and reduce cynicism towards others #bowochallenge #iwartabowochallenge",
 'controlling excessive anxiety',
 "When you hear the song, your heart becomes calm and when you hear the Koran, your heart becomes tense and restless.. it's a sign that your heart is hit by CORONA BLOOD.. you need to think about it.. because life is not a game.",
 'restless restlessness haunts self',
 "The peak period of my stress has passed and I am only noisy now. After going out with my friends yesterday, that makes me feel kinda better. At first I was afraid and anxious to go out, yes, because anxiety is still active. But well I hope I'll gain some weight after this storm, bismillaah",
 "I'm most worried when my mom is sick.",
 "don't worry yet :)",
 '"Yesterday, I was worried half to death, now my wife is aware of being stiff again... how about that?"',
 "The last time I felt this nervous was on Wednesday. When he found out his mother died. I hope this isn't a sign anymore",
 "I don't know how many years it took me to jump in until I could feel the descent without worrying ²",
 "I want to ask, have you ever been worried about the things you like? Even because you really like it, you feel like it's a part of your life. But every time you do or remember it you get worried. What do you think you should do? :(",
 'However, every time I picket, I\'m always nervous: "Even though I\'m just a picket, I\'m really scared, I\'m excited:"',
 "BY GOD I'M STILL WORRY.",
 'time goes on..days go on..at the same time my heart is getting restless and hurt...oh Allah I know you are testing me with this patience, and you are testing me with everything that happens..forgive me who is starting to weaken and lose enthusiasm for keep fighting and survive...',
 'I want to exhale the restlessness in my chest with my breath',
 "Why every morning I want to sleep I'm restless ",
 'Anxious alone, sad alone, not having peace',
 "What's wrong I'm worried, oh I hope it's okay",
 "I really like this, I'm nervous about things I'm not sure about, I don't know why but I feel really nervous. WEIRD.",
 "I'm so nervous, why?",
 'but my heart is still restless even though my mouth is talking',
 "Since then I was restless to the point of choking. What's wrong?",
 "Starting to worry again if you have a lot of schedules, even though yesterday it was neatly arranged. How come biso missed ouch :')",
 "Adf-my does anyone know why I am here? I've been feeling restless since yesterday, like worrying/worrying too much, suddenly feeling sad, just scared. But I also don't know why",
 'Gegana, restless, speechless, I don\'t know what the cause is:"',
 "I'm lazy.. I'm so nervous",
 'Happy but also worried.',
 "It's anxious to worry",
 "Honestly, I'm really nervous",
 'Here from now on, my heart is restless',
 "Later when you are tired of the new one, and then you look back and feel guilty for me, don't be a bit nervous. Trust me, I have forgiven you. Even though I will never accept you again.",
 "I need adit not for stalking or for strange things because I myself have started to learn not to stalk just because I'm afraid that mental disorders will get worse even though I still feel anxious and afraid if I don't stalk, I can hold it so that Adit doesn't feel disturbed",
 'Keep restless astagfirullah',
 "I'm excited but I don't know why, there's no reason, I'm nervous, I have a stomach ache but I'm scared, I know I'm tired, this is the third time today, hah â€” hah :)",
 'Always worried about the future, even though today has not changed.',
 'every time you worry, why is the disease running to your stomach?',
 "If you're nervous looking for the best position before going to sleep, it feels like someone's watching you ™„",
 'Restless and agitated',
 'In the evening, towards the morning. A little worried, a lot of longing',
 "Some days, I don't think I'm doing well, so I feel like I'm really crying, scared, anxious, just sad. until I think of this when I cry, does my fast break or not?",
 "It's been a few days when I sleep by default I'm afraid, restless, nervous, feel alone, sometimes my breath is really heavy.....why is that... like I'm afraid of being restless, oh my God",
 'tired of overtingking, tired of worrying too much, tired of being tired',
 "aren't you worried? aren't you worried? don't you worry...",
 'Instead of getting calmer, this heart is getting more restless',
 "can i tap the dm or not? I'm very nervous thinking",
 'Finally restless again uhh mmhhh ahh',
 'No need to run, just walk one by one the stones that are being stepped on slowly and absorb it without feeling anxious and full of emotions',
 "Lately I'm feeling scared & very anxious thinking about the day for tomorrow's work inspector . Honestly, I'm really scared because I'm not very close to friends, I'm afraid I can't, I'm afraid to disappoint, and if I suddenly remember I cry",
 "This is why I can't sleep, I'm so restless...",
 'I want to exhale the restlessness in my chest with my breath',
 'Restless restlessness accompanies',
 'hlt! why do i like to be nervous tbtb keep worrying so much that i sweat',
 'Not many people are sure of their prayers, not many people are faithful to wait with what is prayed for. Prayer is unique, there is hope and feeling, there is worry and anxiety, there is tears and happiness. But the end of the prayer will always be the best for humans.',
 "I wonder why my heart beats like that sometimes for weeks, then it's back to normal for a few weeks, does anyone know why this isn't it? Or maybe I'm often anxious and stressed, okay?",
 "I'm so nervous I swear, the views are getting slower",
 'Just woke up feeling restless and sore ™„',
 "I'm so worried 5 days of not coming home wey",
 'My life is chaos. There is no solution. Fear of the uncertain. Restless direction.',
 'UNDERSTANDING FEEL FEELING«',
 "I really can't be told to just listen to it for hours. Immediately anxious innate.",
 "I haven't given up… just a little restless.",
 "Actually I'm worried. The original looks really scared. I've come to play/bite my nails :(",
 "If I'm honest, I've been nervous since that day even though I said it wasn't....",
 "Lately, I've been feeling restless and restless. Haihh",
 "I'm so nervous, why isn't it?",
 "The default bat is restless, I don't know why",
 "you know you're restless",
 'Restless,. Locked in all motion. Whipped in the brain noisy debate about decisions. Make friends with fear and risk',
 "Wow, I'm getting restless, let's sleep",
 "I swear I'm so nervous, why don't you",
 'I was a little worried that the afternoon class would actually be able to reach the target. But God just gave a way, wednesday class was moved even though it was a quiz. At least later in the morning you can make out with data until iftar',
 "–¤ When you're anxious or nervous, do you feel like your heart feels weird, doesn't it? Is it just me?",
 "Come on, come on, let's go... 10 years could be passed before, it's not even a month yet, I'm already restless",
 'Time is slow for those who wait, too long for those who are restless, and too short for those who are happy',
 "Restless, restless, become one. Can't agree. Can't even sleep",
 'May May be accompanied by good news. The injured, get well soon. Sorrow turns to love. Quieter anxiety. And prayers that are more patient...#senjamu',
 'Since then, the chicken cake has been restless and wants to lay eggs.',
 'Do not compare yourself to others. Envy only makes restless soul. Be yourself.',
 "The 5 dream ones were moved to a new unit, so why isn't the Anjrit so worried?",
 "finished for the heart's intention to watch the series, I even thought about it. I'm worried",
 '"No regrets or grudges/angry at things that have passed, and don\'t put too much anxiety over the record period #COYS',
 "Usually, if you're restless for a long time, surely after that something will happen or not",
 "Have you ever thought of something and then immediately forgot it then thought you were thinking about this bastard, I don't remember it, so I was restless",
 'Dialogue in the morning.. to yourself, restless and restless accompanying it, hoping someone will understand-',
 "I'm the only one who's nervous.",
 "I'm starting to worry",
 "In my father's family, everyone is smart, I'm sure the expectations for me are also high it makes me very anxious to think about this huhu",
 "Already complete. Disappointed with a broken heart. Produces a sense of restlessness. I don't know, hopefully all of this ends beautifully",
 'when your bipolar relapse welcome shortness of breath, tremors, anxiety, fear, selfharm etc',
 "How come lately I'm not feeling well, like mellow, not calm, restless",
 "When you think about it and don't finish it, it feels really restless",
 "I'm worried.. I'm in a bad mood.. but excited to see law school..",
 "Yes, what will happen later :'), I'm worried that I can control my emotions",
 "I'm really nervous about choosing between boring or chilling, PLEASE",
 "oh my god why have you been a week, you're so nervous, it's really bad aaa",
 "people seem calm, happy like there's no problem because only one smile we throw out but sad, restless and anxious millions of which we keep to ourselves, only we know.",

In [16]:
type(Y)

pandas.core.series.Series

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
Y_reshaped=Y.to_numpy().reshape(-1,1)
encoder=OneHotEncoder(sparse_output=False)
Y_encoded=encoder.fit_transform(Y_reshaped)

In [19]:
(Y_encoded)

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], shape=(52681, 7))

In [20]:
tokenizer=Tokenizer(num_words=20000,oov_token="<OOV>")

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_texts_new,Y_encoded,test_size=0.2,random_state=39)

In [22]:
tokenizer.fit_on_texts(X_train)

In [47]:
my_dict=tokenizer.word_index
next((k for k, v in my_dict.items() if v == 55000), None)

"i'llbe"

In [24]:
Y_test.shape,Y_train.shape,

((10537, 7), (42144, 7))

In [25]:
train_sequenced_text=tokenizer.texts_to_sequences(X_train)
test_sequenced_text=tokenizer.texts_to_sequences(X_test)

In [26]:
sequenced_text=tokenizer.texts_to_sequences(X_texts_new)

In [27]:
len(train_sequenced_text)

42144

In [28]:
sequenced_text

[[601, 6, 5076],
 [958, 658, 1005, 262, 1248, 296, 32, 43, 9, 8845],
 [32, 278, 92, 141, 2306, 578, 1152, 352, 16, 7, 1248, 4, 1248, 285],
 [208, 7321, 6, 691, 3, 101, 177, 17, 77, 95, 421],
 [77, 1248, 4, 1248, 179, 40, 7, 288, 55, 1358, 37, 18, 28, 385],
 [116, 430, 28, 761, 26, 829, 24, 101, 12, 278, 17, 37, 5, 3534],
 [2, 29, 249, 363, 37, 47, 2, 18, 4, 374, 6, 130, 30, 321, 26, 5938],
 [13, 28, 151, 186, 829, 17, 447, 36, 96],
 [2, 911, 1378, 176, 19, 222, 191, 179, 24, 77, 1248, 96, 3394],
 [77, 59, 421, 2, 31, 3, 384],
 [105, 1248, 116, 246, 50, 239, 2, 167, 36, 96, 1211, 278, 1337],
 [77, 1005, 77, 10, 109, 106, 501, 116, 56, 2, 31, 3, 204, 2, 105, 29, 1248],
 [237,
  37,
  12,
  458,
  45,
  68,
  12,
  7,
  356,
  12,
  3,
  1115,
  254,
  28,
  781,
  14,
  68,
  12,
  7,
  356,
  45,
  28,
  362,
  8,
  28,
  29,
  1248,
  24,
  14,
  176,
  8,
  1395,
  43,
  14,
  2,
  95,
  13,
  7,
  279,
  642,
  2061,
  2061,
  2061],
 [38, 21, 488, 12, 28],
 [237,
  179,
  127,
  238,
  212,
  14,
  100,
  28,
  363,
  4,
  398,
  3,
  365,
  127,
  674,
  254,
  28,
  167,
  204],
 [116,
  56,
  2,
  388,
  44,
  77,
  859,
  829,
  4,
  1083,
  254,
  45,
  48,
  28,
  65,
  3,
  170,
  8741],
 [2, 47, 79, 251, 50, 239, 77, 421, 35, 8, 1302, 24, 21],
 [1, 1248, 1248],
 [49,
  3111,
  30,
  10263,
  504,
  34,
  86,
  14,
  13,
  870,
  4,
  10,
  942,
  102,
  73,
  33,
  5,
  369,
  621,
  619,
  7403],
 [35,
  5,
  464,
  12,
  329,
  5,
  410,
  235,
  219,
  329,
  5970,
  63,
  761,
  26,
  109,
  1248,
  4,
  1248,
  2066],
 [208,
  40,
  5,
  193,
  363,
  164,
  155,
  2,
  714,
  5,
  193,
  6043,
  164,
  208,
  126,
  40,
  5,
  193,
  421,
  164,
  155,
  8,
  32,
  510],
 [3016, 522, 34, 7642, 50, 658, 16, 7, 479, 9, 3959, 37, 12, 278, 23, 11],
 [303, 204, 20, 1248, 103, 1670],
 [274, 421, 33, 2314, 44, 5, 512],
 [7,
  242,
  1248,
  7,
  242,
  1248,
  105,
  29,
  841,
  284,
  35,
  2,
  303,
  26,
  5,
  243,
  54,
  208,
  40,
  2066],
 [208, 40, 22, 1248, 129, 21, 400],
 [8, 224, 28, 29, 1248],
 [2316, 17, 1248, 45, 28, 204],
 [96,
  12,
  21,
  7952,
  77,
  274,
  16,
  7,
  128,
  537,
  4,
  90,
  6,
  296,
  305,
  3,
  26,
  2116,
  59,
  659,
  77,
  59,
  829,
  12,
  68,
  101,
  278],
 [63, 12, 134, 1006, 63, 12, 1248, 11865, 1211, 65, 27],
 [77,
  665,
  4,
  4061,
  77,
  297,
  2,
  303,
  752,
  5,
  89,
  85,
  2,
  303,
  752,
  5,
  145,
  254,
  55,
  2,
  25,
  1477,
  10,
  565,
  50,
  250,
  425,
  183,
  77,
  10,
  24,
  37,
  63,
  446,
  22,
  647,
  20,
  941,
  92],
 [2309,
  7,
  1727,
  14,
  224,
  28,
  783,
  167,
  36,
  96,
  794,
  21,
  109,
  9,
  864,
  3959,
  3681,
  438],
 [1, 829, 1],
 [96, 4571, 296, 595, 29, 106, 1617, 363, 1442, 109, 688],
 [179, 7, 1997, 62, 3289, 181, 35, 2, 66, 33, 101, 647, 41, 421, 2, 303, 204],
 [129,
  586,
  586,
  2,
  13,
  10,
  40,
  16,
  5,
  537,
  134,
  1570,
  109,
  1248,
  105,
  1884,
  4,
  218,
  7535,
  116,
  74,
  14,
  268,
  100,
  6,
  307,
  2957,
  156,
  12,
  5,
  3951,
  9,
  2083,
  4,
  2673,
  16,
  537,
  17,
  229,
  2,
  29,
  134,
  1313,
  14,
  21,
  3953,
  2339,
  12,
  115],
 [692,
  63,
  2476,
  3,
  10229,
  33,
  283,
  77,
  22,
  1005,
  37,
  3,
  18,
  308,
  63,
  199,
  167,
  488,
  33,
  283,
  17,
  63,
  616,
  15178,
  33,
  283],
 [109, 22, 1248, 501],
 [601, 424, 77, 1248],
 [17, 6, 296, 12, 95, 1248, 50, 239, 6, 1255, 12, 323],
 [582, 19, 3629, 258, 26, 363],
 [40, 5, 193, 363, 164, 155, 949, 5, 193, 6043, 164],
 [87,
  28,
  151,
  380,
  8,
  45,
  28,
  380,
  8,
  3,
  8490,
  2,
  385,
  5,
  8347,
  5,
  2375,
  179,
  38,
  77,
  24,
  21,
  45,
  2,
  380,
  3647,
  5,
  1739,
  25,
  33,
  226,
  693,
  4904,
  6,
  191,
  714,
  1248,
  4,
  55,
  77,
  249],
 [524,
  2,
  31,
  3,
  196,
  28,
  501,
  208,
  40,
  109,
  1248,
  13,
  958,
  658,
  2,
  3572,
  27,
  1396,
  8,
  487,
  179,
  7,
  1656,
  1053,
  9,
  97,
  2,
  269,
  3,
  196,
  6,
  253,
  7,
  1514,
  185,
  167,
  66,
  102,
  73,
  179,
  10,
  729,
  28,
  41,
  202,
  1023,
  90,
  2,
  2277,
  6580,
  1097],
 [208, 40, 109, 1248, 19, 5, 217, 165, 191, 55, 77, 2148, 24, 124],
 [601,
  49,
  77,
  1248,
  5,
  56,
  51,
  247,
  2,
  694,
  23,
  3236,
  90,
  6,
  296,
  12,
  783,
  116,
  56,
  2,
  3238,
  7,
  1727,
  2,
  167,
  36,
  534,
  16,
  21,
  4301,
  2,
  105,
  31,
  3,
  384,
  38,
  2,
  3238,
  8,
  17,
  2,
  167,
  18,
  8,
  284,
  424,
  2,
  488,
  102,
  73,
  6011],
 [2497, 89, 12, 10, 54, 635, 54, 8, 887],
 [129,
  5,
  1069,
  2,
  911,
  2001,
  6,
  2422,
  19,
  7,
  74,
  2,
  29,
  1248,
  2,
  13,
  7,
  134,
  1188,
  39,
  2972],
 [58,
  84,
  48,
  1248,
  4,
  398,
  47,
  26,
  565,
  62,
  5,
  2277,
  3352,
  9,
  5,
  440,
  4,
  4436,
  5,
  2540],
 [2,
  167,
  36,
  35,
  6,
  262,
  2003,
  163,
  17,
  2,
  167,
  31,
  3,
  66,
  33,
  8,
  96,
  18,
  2,
  29,
  1248],
 [1570, 387, 100, 5, 296, 1248],
 [1755, 10, 26, 829, 52, 33, 8741],
 [110, 76, 4963, 77, 59, 829],
 [1248, 4, 1248],
 [21,
  12,
  5,
  178,
  56,
  208,
  53,
  72,
  89,
  442,
  16,
  6,
  204,
  4,
  8,
  948,
  59,
  106,
  50,
  239,
  77,
  10,
  223,
  33,
  94,
  17,
  77,
  1248],
 [179,
  40,
  7,
  210,
  2,
  29,
  1248,
  4,
  6,
  261,
  219,
  433,
  2,
  31,
  3,
  507,
  198,
  2,
  204],
 [96, 15, 2, 829],
 [363,
  32,
  398,
  398,
  9,
  2291,
  398,
  9,
  6499,
  1438,
  398,
  9,
  1547,
  11814,
  1071,
  15512,
  847,
  834,
  360,
  45,
  48,
  28,
  188],
 [601, 6, 424, 96, 48, 28, 22, 829],
 [387, 9, 3959, 13, 169, 3, 2775, 16024],
 [134, 1248, 1],
 [5,
  191,
  48,
  433,
  9,
  3959,
  23,
  1972,
  14,
  595,
  36,
  5,
  2196,
  1050,
  80,
  47,
  105,
  41,
  37,
  80,
  118,
  4,
  26,
  640,
  5,
  2587,
  19,
  7,
  1131,
  346,
  346,
  1095],
 [397, 511, 388, 44, 397, 511, 388, 44, 1, 5, 1248, 12, 122, 1, 1, 110, 1, 1],
 [501,
  111,
  78,
  40,
  32,
  9,
  7,
  1279,
  794,
  188,
  794,
  279,
  794,
  363,
  794,
  3335,
  794,
  1083,
  794,
  5498,
  360,
  2,
  59,
  167,
  24,
  111,
  14,
  12,
  14134,
  587,
  17,
  37,
  47,
  2,
  18,
  418,
  418,
  418],
 [77,
  22,
  284,
  17,
  47,
  28,
  241,
  11,
  634,
  9,
  2731,
  30,
  10,
  77,
  59,
  421,
  14,
  2,
  303,
  100,
  6,
  604,
  188],
 [2, 167, 24, 942, 2, 167, 24, 1],
 [624, 127, 522, 68, 12, 7, 296, 14, 12, 7595, 582, 3, 480, 62, 28],
 [829, 1248, 1],
 [77, 829, 2, 167, 36, 96, 2, 167, 29, 783],
 [237, 2, 303, 50, 507, 105, 421, 421, 33, 21, 50, 239, 77, 168],
 [8, 219, 4864],
 [77, 22, 1248, 2, 167, 36, 96],
 [74,
  103,
  74,
  14,
  251,
  4633,
  5,
  1346,
  2,
  29,
  5,
  71,
  2,
  1043,
  62,
  28,
  4,
  237,
  2,
  41,
  363,
  38,
  9,
  8,
  3,
  5,
  175,
  14,
  2,
  714,
  421,
  421,
  14,
  8,
  57,
  7786,
  6,
  1775,
  505,
  3722,
  4117],
 [1,
  78,
  7,
  2389,
  77,
  274,
  279,
  4,
  1248,
  1211,
  71,
  21,
  242,
  410,
  78,
  7,
  2389,
  418,
  418,
  418],
 [52,
  218,
  191,
  13,
  28,
  40,
  109,
  1248,
  34,
  246,
  4,
  16,
  5,
  2406,
  127,
  262,
  12,
  556,
  96],
 [62, 55, 27, 179, 10, 59, 106, 76, 1248, 12, 168, 103, 1670],
 [2,
  911,
  1378,
  312,
  4,
  55,
  6,
  261,
  519,
  22,
  128,
  77,
  2316,
  17,
  2,
  303,
  204,
  208,
  197,
  3,
  13698,
  17,
  77,
  1248],
 [102, 363, 102, 421, 102, 249],
 [1248, 4, 4294],
 [68, 51, 105, 26, 783, 16, 5, 6002, 9, 3959],
 [1, 1442, 363],
 [21,
  12,
  96,
  6,
  296,
  12,
  2116,
  22,
  659,
  134,
  1248,
  17,
  2,
  167,
  36,
  37,
  77,
  421,
  33,
  179,
  7,
  357,
  109],
 [71, 1248, 1050, 270, 84, 48, 68, 48, 373, 601, 3373, 2531, 119, 7943, 1, 1],
 [35, 6, 104, 13, 3145, 3, 6, 2825, 14, 78, 72, 1634, 77, 421],
 [77, 1896, 899, 5498, 1248],
 [1279, 3959, 96, 48, 28],
 [5067,
  277,
  330,
  507,
  1248,
  170,
  7,
  5057,
  9,
  5547,
  4,
  713,
  75,
  599,
  906,
  2,
  59,
  118,
  3,
  26,
  234,
  3,
  445,
  21,
  262],
 [205, 77, 1, 89, 1, 1, 131],
 [363],
 [179, 22, 1248, 93],
 [12, 68, 108, 84, 45, 329, 303, 204, 176, 17, 5067, 16361],
 [258, 488, 254, 28, 31, 3, 384],
 [1459,
  27,
  2467,
  1,
  429,
  3685,
  27,
  65,
  2405,
  285,
  1,
  8781,
  1,
  4,
  254,
  55,
  888,
  1,
  2203,
  222,
  4400,
  7085,
  2046,
  95,
  16,
  204,
  2315,
  17,
  77,
  829,
  1800],
 [77,
  829,
  45,
  28,
  247,
  351,
  89,
  4,
  381,
  363,
  77,
  71,
  421,
  534,
  2,
  51,
  170,
  3,
  146,
  245,
  1371,
  62,
  28,
  131,
  1035,
  69,
  183,
  62,
  6,
  1],
 [52,
  421,
  15,
  2,
  431,
  6,
  120,
  244,
  254,
  8,
  25,
  910,
  7845,
  53,
  7,
  106,
  185,
  567],
 [1248, 359, 3, 2733, 102, 158, 4, 313, 254, 923, 3, 204],
 [179, 24, 9735, 44, 9735, 411, 17, 2, 167, 36, 37, 8, 219, 22, 1248],
 [49,
  3111,
  30,
  10263,
  504,
  34,
  86,
  14,
  13,
  870,
  4,
  10,
  942,
  102,
  73,
  33,
  5,
  369,
  621,
  619,
  7403],
 [19, 8758, 1773, 77, 22, 168, 9, 942],
 [19,
  277,
  91,
  966,
  23,
  21,
  1230,
  7595,
  612,
  35,
  7,
  165,
  191,
  404,
  111,
  51,
  351,
  2,
  167,
  36,
  265,
  1438,
  9,
  1183],
 [109, 7, 242, 363, 229],
 [10,
  5911,
  30,
  1130,
  10263,
  504,
  34,
  86,
  14,
  13,
  870,
  4,
  10,
  942,
  102,
  73,
  33,
  5,
  369,
  621,
  619,
  7403],
 [258, 26, 363, 8, 761, 623, 24, 21],
 [5271, 2, 167, 36, 37, 3, 18, 17, 77, 829],
 [134, 1248, 303, 204, 4904],
 [77,
  279,
  38,
  2,
  303,
  4256,
  94,
  17,
  2,
  24,
  3,
  1941,
  116,
  74,
  38,
  77,
  168,
  9,
  281,
  180,
  9,
  1147,
  2,
  121,
  5,
  306,
  12,
  148,
  1762,
  587,
  2,
  15,
  148,
  71,
  4,
  71,
  1248],
 [116,
  56,
  110,
  6303,
  96,
  761,
  21,
  296,
  26,
  1248,
  54,
  35,
  8,
  303,
  866,
  5,
  407,
  17,
  23,
  21,
  407,
  28,
  303,
  18,
  94,
  35,
  28,
  18,
  8,
  8,
  47,
  79,
  100,
  86,
  206],
 [96, 48, 28, 1248, 4, 1248, 2361, 1446],
 [77, 22, 829, 33, 37, 3, 18],
 [10976, 1248, 3170, 12, 278, 23, 4679],
 [2, 1834, 2, 303, 204, 204, 450, 17, 2, 167, 204, 22, 1248],
 [96,
  133,
  8,
  372,
  24,
  692,
  77,
  1248,
  279,
  24,
  2,
  31,
  3,
  384,
  17,
  2,
  167,
  36,
  37,
  3,
  26,
  279,
  33],
 [96,
  22,
  829,
  37,
  12,
  907,
  12,
  10,
  38,
  4969,
  12,
  245,
  1,
  17,
  179,
  32,
  38,
  9,
  28],
 [5,
  4512,
  12,
  6301,
  17,
  2350,
  89,
  38,
  5,
  3001,
  12,
  10,
  1435,
  47,
  26,
  1955,
  19,
  5,
  296],
 [303, 28, 10, 7786, 2049, 648, 254, 77, 363, 4, 303, 204],
 [52, 18, 28, 171, 8, 783, 3128, 10976, 12, 1083, 4, 90, 988, 5074, 30, 829],
 [4, 131, 794, 109, 829, 4, 363, 245, 547, 96],
 [77, 10, 109, 134, 106, 21, 400, 77, 59, 421, 1446],
 [35,
  28,
  48,
  1248,
  1248,
  20,
  1941,
  3,
  127,
  1,
  4,
  380,
  5,
  1,
  22,
  14,
  5,
  296,
  1725,
  1201,
  4,
  2424,
  13622,
  766,
  304,
  1,
  1],
 [2497, 3240, 89],
 [45,
  28,
  480,
  5,
  1727,
  127,
  296,
  1725,
  783,
  4,
  45,
  28,
  480,
  5,
  1,
  127,
  296,
  1725,
  2883,
  4,
  1248,
  179,
  7,
  1271,
  14,
  127,
  296,
  12,
  506,
  103,
  5164,
  527,
  28,
  118,
  3,
  66,
  33,
  8,
  38,
  39,
  12,
  10,
  7,
  805],
 [1248, 3959, 5511, 244],
 [5,
  3597,
  926,
  9,
  6,
  282,
  78,
  870,
  4,
  2,
  15,
  79,
  6268,
  55,
  110,
  65,
  43,
  23,
  6,
  104,
  586,
  14,
  224,
  11,
  29,
  1087,
  114,
  34,
  178,
  2,
  25,
  398,
  4,
  363,
  3,
  69,
  43,
  587,
  38,
  89,
  12,
  95,
  1544,
  17,
  176,
  2,
  251,
  647,
  1426,
  82,
  564,
  110,
  21,
  3480,
  1],
 [77, 193, 421, 45, 6, 253, 12, 329],
 [167, 488, 312],
 [586,
  2,
  25,
  421,
  494,
  3,
  332,
  55,
  6,
  762,
  12,
  984,
  9,
  76,
  4657,
  131,
  52,
  33,
  14],
 [5,
  136,
  56,
  2,
  186,
  21,
  829,
  25,
  27,
  2629,
  45,
  63,
  339,
  43,
  209,
  390,
  579,
  2,
  251,
  21,
  1011,
  7,
  1271,
  85],
 [2,
  167,
  36,
  52,
  218,
  91,
  8,
  348,
  11,
  3,
  1234,
  16,
  254,
  2,
  88,
  29,
  5,
  9810,
  245,
  942,
  6374],
 [2,
  31,
  3,
  338,
  13,
  28,
  151,
  40,
  421,
  33,
  5,
  86,
  28,
  24,
  50,
  38,
  28,
  59,
  24,
  8,
  28,
  29,
  24,
  179,
  7,
  316,
  9,
  127,
  39,
  17,
  116,
  56,
  28,
  18,
  30,
  362,
  8,
  28,
  41,
  421,
  37,
  18,
  28,
  66,
  28,
  159,
  18],
 [460,
  116,
  56,
  2,
  1,
  77,
  105,
  829,
  50,
  239,
  77,
  20,
  7,
  1,
  77,
  59,
  249,
  77,
  1083],
 [103, 424, 77, 95, 488],
 [56,
  529,
  27,
  191,
  69,
  27,
  34,
  5,
  213,
  56,
  6,
  296,
  12,
  148,
  1248,
  4,
  297,
  601,
  3373,
  2,
  36,
  28,
  48,
  3062,
  11,
  23,
  21,
  3210,
  4,
  28,
  48,
  3062,
  11,
  23,
  111,
  14,
  548,
  1506,
  11,
  84,
  12,
  429,
  3,
  17869,
  4,
  542,
  6258,
  19,
  171,
  875,
  4,
  1090],
 [2, 31, 3, 7545, 5, 3959, 16, 6, 514, 23, 6, 1106],
 [96, 116, 400, 2, 31, 3, 204, 77, 1248],
 [363, 184, 279, 184, 10, 154, 709],
 [1211, 278, 77, 421, 601, 2, 251, 179, 373],
 [2,
  59,
  24,
  21,
  77,
  829,
  33,
  86,
  77,
  10,
  240,
  33,
  2,
  167,
  36,
  96,
  17,
  2,
  29,
  59,
  829,
  411],
 [77, 22, 829, 96],
 [17, 6, 296, 12, 95, 1248, 50, 239, 6, 1255, 12, 323],
 [129, 90, 2, 25, 1248, 3, 5, 175, 9, 4725, 1211, 278],
 [429,
  3,
  488,
  131,
  35,
  28,
  13,
  7,
  161,
  9,
  5861,
  50,
  239,
  586,
  8,
  25,
  14793,
  6736,
  52,
  247,
  1,
  1243,
  6747,
  2066],
 [1,
  6,
  133,
  108,
  36,
  96,
  2,
  15,
  122,
  208,
  40,
  109,
  1248,
  129,
  586,
  24,
  942,
  942,
  102,
  73,
  794,
  109,
  279,
  20,
  249,
  17,
  2,
  126,
  167,
  36,
  96],
 [1, 1248, 14492, 2, 167, 36, 37, 5, 617, 12],
 [77, 923, 77, 22, 829],
 [188, 17, 126, 421],
 [179, 363, 3, 488],
 [382, 77, 59, 829],
 [122, 62, 55, 27, 6, 296, 12, 1248],
 [404,
  45,
  28,
  48,
  168,
  9,
  5,
  220,
  64,
  4,
  90,
  28,
  276,
  92,
  4,
  29,
  841,
  19,
  11,
  167,
  26,
  7,
  319,
  829,
  646,
  11,
  2,
  13,
  6122,
  28,
  50,
  239,
  2,
  51,
  75,
  866,
  28,
  131],
 [2,
  118,
  1,
  10,
  19,
  7917,
  30,
  19,
  1337,
  86,
  38,
  2,
  42,
  13,
  169,
  3,
  896,
  10,
  3,
  9589,
  20,
  38,
  77,
  398,
  14,
  226,
  2002,
  51,
  41,
  206,
  50,
  239,
  2,
  95,
  29,
  363,
  4,
  398,
  35,
  2,
  167,
  9589,
  2,
  47,
  622,
  8,
  22,
  14,
  1,
  595,
  29,
  5825],
 [171, 1248, 13281],
 [77,
  1083,
  17,
  2,
  167,
  36,
  96,
  876,
  49,
  256,
  77,
  829,
  2,
  13,
  7,
  711,
  2454,
  17,
  77,
  249,
  2,
  36,
  77,
  168,
  21,
  12,
  5,
  1616,
  56,
  229,
  7773,
  19096,
  7773],
 [105, 421, 33, 5, 369, 50, 239, 229, 78, 10, 746],
 [116, 56, 28, 488, 96, 12, 5, 1071, 935, 3, 127, 711],
 [35,
  988,
  829,
  309,
  19,
  5,
  243,
  1373,
  155,
  65,
  3,
  204,
  8,
  219,
  24,
  5910,
  710,
  28,
  19894],
 [1248, 4, 4294],
 [16, 5, 1813, 766, 5, 400, 7, 242, 421, 7, 161, 9, 3919],
 [82,
  191,
  2,
  167,
  66,
  77,
  157,
  176,
  22,
  2,
  29,
  24,
  77,
  59,
  422,
  249,
  363,
  20,
  279,
  254,
  2,
  66,
  9,
  21,
  45,
  2,
  384,
  133,
  6,
  659,
  430,
  30,
  10],
 [179,
  40,
  7,
  165,
  191,
  45,
  2,
  204,
  103,
  4793,
  77,
  398,
  1248,
  829,
  29,
  184,
  237,
  6,
  1106,
  12,
  59,
  1188,
  96,
  12,
  14,
  24,
  77,
  398,
  9,
  76,
  1248,
  601,
  6,
  424],
 [168, 9, 1, 168, 9, 942, 102, 73, 168, 9, 76, 168],
 [2022, 28, 421, 2022, 28, 421, 167, 28, 488],
 [453, 9, 148, 6903, 21, 296, 12, 148, 71, 1248],
 [47, 2, 4548, 5, 2910, 30, 10, 77, 134, 829, 223],
 [311, 1248, 131, 9677, 1, 8162],
 [49,
  118,
  3,
  684,
  20,
  694,
  64,
  103,
  64,
  5,
  6014,
  14,
  48,
  76,
  5037,
  27,
  724,
  4,
  9916,
  8,
  245,
  109,
  363,
  4,
  433,
  9,
  576],
 [501,
  77,
  109,
  249,
  134,
  363,
  223,
  33,
  5,
  74,
  19,
  11978,
  93,
  18983,
  382,
  77,
  59,
  249,
  38,
  77,
  10,
  134,
  365,
  3,
  104,
  77,
  398,
  2,
  303,
  77,
  398,
  3,
  3562,
  4,
  35,
  2,
  794,
  362,
  2,
  384],
 [21, 12, 96, 2, 303, 204, 77, 22, 1248],
 [2, 31, 3, 7545, 5, 3959, 16, 6, 514, 23, 6, 1106],
 [1248, 3959, 10530],
 [1, 96, 18, 2, 24, 3, 26, 829, 10976, 171, 942, 22, 73, 14, 2, 3411],
 [10,
  218,
  58,
  48,
  240,
  9,
  194,
  4770,
  10,
  218,
  58,
  48,
  9173,
  3,
  594,
  23,
  37,
  12,
  5131,
  19,
  3972,
  12,
  3849,
  68,
  12,
  251,
  4,
  109,
  68,
  12,
  488,
  4,
  89,
  68,
  12,
  1246,
  4,
  608,
  17,
  5,
  149,
  9,
  5,
  3972,
  51,
  105,
  26,
  5,
  243,
  19,
  1738],
 [2,
  789,
  96,
  6,
  296,
  3161,
  24,
  14,
  237,
  19,
  300,
  90,
  179,
  92,
  3,
  291,
  19,
  7,
  165,
  300,
  133,
  108,
  36,
  96,
  21,
  1011,
  8,
  30,
  207,
  77,
  432,
  363,
  4,
  589,
  373],
 [77, 22, 829, 2, 1834, 5, 3357, 48, 148, 5545],
 [20, 802, 44, 109, 1248, 4, 1745, 19894],
 [77, 22, 421, 346, 191, 9, 10, 441, 231, 1],
 [6, 39, 12, 3610, 68, 12, 49, 1423, 350, 9, 5, 4572, 1248, 2196],
 [1250, 29, 1],
 [2, 59, 303, 26, 190, 3, 20, 764, 3, 8, 19, 330, 974, 363, 9777],
 [2, 911, 640, 1, 20, 7, 242, 1248],
 [235, 77, 421, 5, 3128, 852, 59, 249, 208, 247, 3, 592, 2994, 6, 3975],
 [35, 77, 914, 208, 40, 829, 129, 14, 74, 50, 239, 2, 199, 8, 948],
 [501, 208, 40, 109, 1248, 4, 1248, 1],
 [77, 22, 829, 96, 1011, 8],
 [5, 4793, 3751, 12, 1248, 2, 167, 36, 96],
 [28, 36, 988, 1248],
 [1248,
  2012,
  16,
  32,
  4584,
  15517,
  16,
  5,
  307,
  6268,
  6853,
  33,
  1645,
  100,
  104,
  23,
  350,
  4,
  1480],
 [1925, 77, 148, 1248, 1755, 204],
 [2, 1834, 77, 22, 829, 96, 167, 28],
 [2,
  25,
  7,
  242,
  421,
  14,
  5,
  2406,
  620,
  57,
  235,
  26,
  234,
  3,
  814,
  5,
  3951,
  17,
  424,
  20,
  530,
  7,
  113,
  2629,
  620,
  25,
  567,
  50,
  239,
  8,
  25,
  7,
  6390,
  34,
  327,
  404,
  16,
  5,
  400,
  28,
  47,
  100,
  43,
  23,
  3172,
  254,
  1],
 [1,
  45,
  988,
  363,
  30,
  829,
  18,
  28,
  29,
  24,
  127,
  296,
  219,
  411,
  595,
  8,
  12,
  8,
  20,
  11],
 [247,
  27,
  247,
  27,
  1755,
  69,
  448,
  91,
  88,
  26,
  870,
  155,
  179,
  10,
  50,
  7,
  288,
  312,
  77,
  274,
  1248],
 [56,
  12,
  1199,
  19,
  270,
  84,
  594,
  102,
  158,
  19,
  270,
  84,
  48,
  1248,
  4,
  102,
  544,
  19,
  270,
  84,
  48,
  188],
 [1248, 1248, 381, 64, 303, 2013, 303, 50, 204],
 [374,
  374,
  26,
  5379,
  103,
  106,
  1371,
  5,
  3816,
  41,
  176,
  379,
  3955,
  1395,
  3,
  145,
  8637,
  89,
  4,
  4770,
  14,
  48,
  71,
  1756,
  1],
 [129, 90, 5, 3149, 3226, 78, 40, 1248, 4, 446, 3, 1061, 7656],
 [18, 10, 3029, 467, 3, 304, 2914, 79, 224, 1248, 1285, 26, 467],
 [5,
  346,
  615,
  664,
  172,
  567,
  3,
  7,
  220,
  3899,
  22,
  96,
  1011,
  5,
  15193,
  22,
  421],
 [1435, 19, 5, 1, 2764, 3, 638, 5, 2821, 2, 50, 160, 33, 8, 77, 421],
 [49,
  3111,
  30,
  10263,
  504,
  34,
  86,
  14,
  13,
  870,
  4,
  167,
  280,
  102,
  73,
  89,
  115,
  5,
  2371,
  926,
  1],
 [454, 35, 988, 1248, 19, 7, 158, 56, 2439, 110, 14, 101, 51, 415, 30, 10],
 [13,
  28,
  151,
  160,
  9,
  101,
  4,
  90,
  974,
  1355,
  8,
  90,
  160,
  28,
  172,
  223,
  33,
  21,
  5130,
  2,
  167,
  362,
  8,
  22,
  2,
  25,
  1248],
 [9588, 16, 5, 400, 3, 467, 1248, 4, 1248, 8887, 8, 798, 124, 51, 299],
 [77, 5, 79, 64, 3306, 829],
 [77, 429, 3, 488],
 [16,
  6,
  4302,
  130,
  156,
  12,
  1261,
  77,
  240,
  5,
  2017,
  19,
  11,
  48,
  126,
  313,
  8,
  224,
  11,
  134,
  363,
  3,
  66,
  33,
  21,
  10767],
 [274,
  918,
  1442,
  23,
  7,
  665,
  296,
  11170,
  7,
  474,
  9,
  3959,
  2,
  167,
  36,
  1050,
  32,
  9,
  21,
  1281,
  11886],
 [45, 127, 335, 2402, 2018, 3312, 9, 1106, 6762, 89, 350, 7491, 360],
 [52, 247, 501, 77, 10, 109, 176, 24, 19541, 10, 783, 1248],
 [45, 28, 66, 33, 8, 4, 167, 1109, 8, 8, 219, 59, 1248],
 [77, 421, 77, 16, 7, 128, 537, 17, 1083, 3, 121, 2025, 181],
 [587, 37, 51, 415, 404, 2066, 77, 421, 14, 2, 47, 445, 6, 576],
 [77, 59, 829, 33, 3057, 584, 1178, 30, 7621, 258],
 [601, 6, 424, 96, 13, 28, 40, 7, 210, 988, 22, 829, 179, 59, 128, 11776],
 [58,
  372,
  783,
  188,

In [29]:
sent_max_len=max(len(sent) for sent in sequenced_text)

In [30]:
sent_max_len

6300

In [29]:
train_padded_text=pad_sequences(train_sequenced_text,maxlen=100)
test_padded_text=pad_sequences(test_sequenced_text,maxlen=100)

In [30]:
print(train_padded_text)

[[   0    0    0 ...    4  279   56]
 [   0    0    0 ...    6 1503 1025]
 [   0    0    0 ...    8   76   14]
 ...
 [   0    0    0 ... 2637   23    1]
 [  69   27    3 ...   46   48   92]
 [   2   13   21 ...   15   95  162]]

In [31]:
dim=100
voc_size=len(tokenizer.word_index)+1
voc_size

55689

In [34]:
model=Sequential([
        Embedding(20000,dim),
        SpatialDropout1D(0.5),                   # better than Dropout for embeddings
        Bidirectional(GRU(32, recurrent_dropout=0.3,kernel_regularizer=regularizers.l2(1e-5))),   # single LSTM layer, not stacked
        Dropout(0.4),
        Dense(32, activation='relu', kernel_regularizer=regularizers.l2(1e-4)),
        Dropout(0.3),
        Dense(7, activation='softmax')
    ])

In [35]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout1d               │ ?                      │             0 │
│ (SpatialDropout1D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
stopping_callback=EarlyStopping(monitor='val_loss',patience=4  ,restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6)

In [ ]:
history=model.fit(train_padded_text,Y_train, validation_data=(test_padded_text,Y_test),epochs=50,batch_size=32,callbacks=[stopping_callback,reduce_lr],shuffle=True)

In [ ]:
y_pred=model.predict(test_padded_text)

330/330 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step

In [ ]:
y_pred.shape

(10537, 7)

In [ ]:
sample_text=["""We're officially making r/gamesonreddit open for direct posting! We want to trial providing a space that allows developers to share their creations, updates to their games, or key events happening. 

We’ll evaluate how successful it is at this over the next several weeks. Feel free to share feedback and ideas in the comments as well. 

Introducing new rules: 

To ensure a topical and balanced environment, we're implementing a few new rules related to staying on topic and overpromotion.

Stay on topic: This community is focused on discussion around games built on Reddit’s Developer Platform. Please keep posts and comments relevant! 

No overpromotion: Please refrain from excessive overpromotion or spamming your game. We want genuine engagement and discussion, not just repeated self-promotion. While we encourage developers to share their work, please be mindful of this rule and focus on quality contributions and meaningful interactions.."""]
seq = tokenizer.texts_to_sequences(sample_text)

# Pad it to same length as training
padded = pad_sequences(seq, maxlen=100)

In [ ]:
seq

[[1954,
  2262,
  287,
  1155,
  1,
  538,
  19,
  3031,
  985,
  80,
  31,
  3,
  3944,
  4802,
  7,
  928,
  14,
  4709,
  1,
  3,
  591,
  194,
  11356,
  6783,
  3,
  194,
  822,
  30,
  2283,
  1629,
  660,
  6671,
  6716,
  52,
  1215,
  8,
  12,
  34,
  21,
  115,
  5,
  302,
  786,
  300,
  29,
  555,
  3,
  591,
  2659,
  4,
  1338,
  16,
  5,
  1535,
  54,
  176,
  9164,
  220,
  2155,
  3,
  4120,
  7,
  1,
  4,
  5623,
  1557,
  1954,
  1,
  7,
  165,
  220,
  2155,
  900,
  3,
  1093,
  27,
  1739,
  4,
  1,
  352,
  27,
  1739,
  21,
  1104,
  12,
  2259,
  27,
  3096,
  174,
  822,
  2112,
  27,
  1,
  7763,
  4289,
  258,
  171,
  1399,
  4,
  1535,
  3854,
  49,
  1,
  258,
  13017,
  62,
  3240,
  1,
  30,
  14495,
  127,
  805,
  80,
  31,
  1982,
  6870,
  4,
  3096,
  10,
  20,
  4749,
  244,
  4415,
  198,
  80,
  3178,
  1,
  3,
  591,
  194,
  93,
  258,
  26,
  7498,
  9,
  21,
  3008,
  4,
  691,
  27,
  2368,
  14363,
  4,
  2225,
  2763]]

In [ ]:
print(padded)

[[  555     3   591  2659     4  1338    16     5  1535    54   176  9164
    220  2155     3  4120     7     1     4  5623  1557  1954     1     7
    165   220  2155   900     3  1093    27  1739     4     1   352    27
   1739    21  1104    12  2259    27  3096   174   822  2112    27     1
   7763  4289   258   171  1399     4  1535  3854    49     1   258 13017
     62  3240     1    30 14495   127   805    80    31  1982  6870     4
   3096    10    20  4749   244  4415   198    80  3178     1     3   591
    194    93   258    26  7498     9    21  3008     4   691    27  2368
  14363     4  2225  2763]]

In [ ]:
# Model prediction
pred = model.predict(padded)

pred_class = np.argmax(pred, axis=1)[0]
print("Predicted class index:", pred_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Predicted class index: 5

In [ ]:
pred_label = encoder.inverse_transform(pred)
print("Predicted label:", pred_label[0][0])

Predicted label: Stress